# Generated by Django 4.1.5 on 2023-04-29 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_buyer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "paymentmode",
                    models.IntegerField(
                        choices=[(0, "COD"), (1, "Net Banking")], default=0
                    ),
                ),
                (
                    "paymentstatus",
                    models.IntegerField(
                        choices=[(0, "Pending"), (1, "Done")], default=0
                    ),
                ),
                (
                    "orderstatus",
                    models.IntegerField(
                        choices=[
                            (0, "Order Placed"),
                            (1, "Ready to Pack"),
                            (2, "Packed"),
                            (3, "Ready to Ship"),
                            (4, "Shipped"),
                            (5, "Order in Transit"),
                            (6, "Product reached at final destination"),
                            (7, "Out for Delievery"),
                            (8, "Delievery"),
                        ],
                        default=0,
                    ),
                ),
                ("subtotal", models.IntegerField()),
                ("shipping", models.IntegerField()),
                ("total", models.IntegerField()),
                (
                    "rppid",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.buyer"
                    ),
                ),
            ],
        ),
    ]
