# Generated by Django 4.1.5 on 2023-04-29 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_checkout"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="CheckoutProduct",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.checkout",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.product",
                    ),
                ),
            ],
        ),
    ]
