# Generated by Django 4.1.5 on 2023-04-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutproduct",
            name="qty",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="checkoutproduct",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
